env:
  es6: true
  browser: true
  node: true
extends: 
  - 'airbnb'

parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

rules:
  indent:
    - error
    - 2
  semi:
    - error
    - always
  no-console: 0
  linebreak-style: 0
  