plugins:
  - react

env:
  es6: true
  browser: true
  node: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'

parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

rules:
  indent:
    - error
    - 2
  semi:
    - error
    - always
  no-console: 0